### 새로운 Car 등록
POST http://localhost:3000/cars
Content-Type: application/json

{
"carNumber": "123431231",
"manufacturer": "HYUNDAI",
"model": "SONATA",
"manufacturingYear": 2020,
"mileage": 10000,
"price": 20000,
"accidentCount": 0,
"explanation": "New car",
"accidentDetails": "",
"carStatus" : "POSSESSION"
}
